---
title: "Species Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---
```{r loaddata, include = FALSE, message = FALSE}
library(tidyverse)
library(readr)
library(readxl)
library(purrr)
library(magrittr)

LPI_data<-read.csv('../dataset/LPR2020data_public.csv')%>%
  mutate(Subspecies=ifelse(Subspecies=="NULL"|nchar(Subspecies)==0,NA,Subspecies))

LPI_only_obs<-LPI_data%>%
  pivot_longer(starts_with("X"),names_to="Year", values_to="Count")%>%
  group_by(ID)%>%
  filter(!Count=='NULL')%>%
  mutate(Year=sub('.', '', Year))

LPI_only_obs$ID<-as.factor(LPI_only_obs$ID)
LPI_only_obs$Count<-as.numeric(LPI_only_obs$Count)
LPI_only_obs$Year<-as.double(LPI_only_obs$Year)

redlist_data<-read.csv('../dataset/redlistspecies.csv')

redlist_data$scientificName <- gsub(" ", "_", redlist_data$scientificName)

#join livingplanet with redlist
merged_data<-left_join(LPI_data,redlist_data, by=c('Binomial'='scientificName'))

#pivot
merged_timeseries<-merged_data%>%
  pivot_longer(starts_with("X"),names_to="Year", values_to="Count")%>%
  group_by(ID)%>%
  filter(!Count=='NULL')%>%
  mutate(Year=sub('.', '', Year))

#set classes
merged_timeseries$ID<-as.factor(merged_timeseries$ID)
merged_timeseries$Year<-as.double(merged_timeseries$Year)
merged_timeseries$Count<-as.numeric(merged_timeseries$Count)
merged_timeseries$redlistCategory <- factor(merged_timeseries$redlistCategory, levels = c(NA, 'Data Deficient', 'Lower Risk/least concern', 'Least Concern', 'Lower Risk/conservation dependent', 'Lower Risk/near threatened', 'Near Threatened', 'Vulnerable', 'Endangered', 'Critically Endangered', 'Extinct in the Wild', 'Extinct'))
merged_data$redlistCategory <- factor(merged_data$redlistCategory, levels = c(NA, 'Data Deficient', 'Lower Risk/least concern', 'Least Concern', 'Lower Risk/conservation dependent', 'Lower Risk/near threatened', 'Near Threatened', 'Vulnerable', 'Endangered', 'Critically Endangered', 'Extinct in the Wild', 'Extinct'))

## brRead

### These functions help read nested brackets for expenditure data

# These functions help read nested brackets

lastBrRead<-function(string){
  #lastBrRead reads the last outermost bracket
  #Example: "welcome (home) (my(lovely) gator)" %>% lastbrRead() returns "my(lovely) gator"
  openBr=0
  startpos=0
  endpos=0
  string_list<-unlist(strsplit(string, split = ""))
  for(pos in 1:nchar(string)){
    if(string_list[pos]=="("){
      if (openBr==0){
        startpos=pos
      }
      openBr<-openBr+1
    } else if(string_list[pos]==")"){
      if (openBr==1){
        endpos=pos
      }
      openBr<-openBr-1
    }
  }
  string<-substr(string,startpos+1,endpos-1)
  return(string)
}

rmBrRead<-function(string){
  if (nchar(string)==0) {return(string)}
  #rmBrRead removes any inner brackets
  #Example: "my(lovely) gator" %>% rmBrRead() returns "my gator"
  string_list<-unlist(strsplit(string, split = ""))
  openBr=0
  cutstartpos=0
  cutendpos=0
  for(pos2 in 1:nchar(string)){
    if(string_list[pos2]=="("){
      if (openBr==0){
        cutstartpos=pos2
      }
      openBr<-openBr+1
    } else if(string_list[pos2]==")"){
      if (openBr==1){
        cutendpos=pos2
      }
      openBr<-openBr-1
    }
  }
  string<-paste(substr(string, 1,cutstartpos-1), substr(string, cutendpos+1,nchar(string)), sep="")
  return(string)
}

brRead<-function(string){
  #"welcome (home) (my(lovely) gator)" %>% brRead() returns "my gator" 
  return(rmBrRead(lastBrRead(string)))
}


# expenditures_200X


#2000
expen_2000<-read_excel('../dataset/expen/expenditure_2000.xlsx',3)
expenditures_2000<-expen_2000%>%
  rename(Common_name="SPECIES NAME (50 CFR PART 17)", Scientific="SCIENTIFIC NAME", Class="RANK", FWS_total="FWS TOTAL", Other_fed="OTHER FED", Fed_total="FED TOTAL", States_total="STATES TOTAL", Species_total="SPECIES TOTAL ($000)")%>% #rename variables
  filter(!is.na(Common_name))%>%
  filter(!is.na(Class))%>%
  mutate(temp=cumsum(Class=='Clams'))%>%
  filter(temp==0)%>% #select rows before "Fishes subtotal"
  select(-temp)%>%
  filter(!is.na(Scientific))

expenditures_2000<-expenditures_2000%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>%
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA))%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  mutate(Year=2000)%>%
  mutate(FWS_total=FWS_total*1000, Other_fed=Other_fed*1000, Fed_total=Fed_total*1000, States_total=States_total*1000, Species_total=Species_total*1000)%>%
  data.frame()


#2001
expen_2001<-read_excel('../dataset/expen/expenditure_2001.xlsx',5)

expenditures_2001<-expen_2001%>%
  rename(Species_sci="Species (50 CFR Part 17)", Class="Class",FWS_total="FWS\r\nTotal ($)", Other_fed="Other Fed ($)", Fed_total="Fed Total ($)", States_total="States Total ($)", Species_total="Species Total ($)")%>% #rename variables
  filter(!is.na(Species_sci))%>%
  filter(!is.na(Class))%>%
  mutate(temp=cumsum(Class=='Clams'))%>%
  filter(temp==0)%>% #select rows before "Fishes subtotal"
  select(-temp)

expenditures_2001<-expenditures_2001%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2001)%>%
  data.frame()


#2002
expen_2002<-read_excel('../dataset/expen/expenditure_2002.xlsx',5)

expenditures_2002<-expen_2002%>%
  rename(Species_sci="Species (50 CFR Part 17)", FWS_total="FWS\r\nTotal ($)", Other_fed="Other Fed ($)", Fed_total="Fed Total ($)", States_total="States Total ($)", Species_total="Species Total ($)")%>% #rename variables
  filter(!is.na(Species_sci))%>%
  filter(!is.na(Class))%>%
  mutate(temp=cumsum(Class=='Clams'))%>%
  filter(temp==0)%>% #select rows before "Clams"
  select(-temp)


expenditures_2002<-expenditures_2002%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2002)%>%
  data.frame()


#2003
expen_2003<-read_excel('../dataset/expen/expenditure_2003.xlsx',5)

expenditures_2003<-expen_2003%>%
  rename(Species_sci="Species (50 CFR Part 17)", Status="Stat- us", FWS_total="FWS\r\nTotal ($)", Other_fed="Other Fed ($)", Fed_total="Fed Total ($)", States_total="States Total ($)", Species_total="Species Total ($)")%>% #rename variables
  filter(!is.na(Species_sci))%>%
  filter(!is.na(Class))%>%
  mutate(temp=cumsum(Class=="Clams"))%>%
  filter(temp==0)%>% #select rows before "Fishes subtotal"
  select(-temp)

expenditures_2003<-expenditures_2003%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2003)%>%
  data.frame()


#2004
expen_2004<-read_excel('../dataset/expen/expenditure_2004.xlsx',5)

expenditures_2004<-expen_2004%>%
  rename(Species_sci="Species (50 CFR Part 17)", FWS_total="FWS\r\nTotal", Other_fed="Other Fed", Fed_total="Fed Total", States_total="States Total", Species_total="Species Total")%>% #rename variables
  filter(!is.na(Species_sci))%>%
  filter(!is.na(Class))%>%
  mutate(temp=cumsum(Class=='Clams'))%>%
  filter(temp==0)%>% #select rows before "Fishes subtotal"
  select(-temp)

expenditures_2004<-expenditures_2004%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2004)%>%
  data.frame()


#2005
expen_2005<-read_excel('../dataset/expen/expenditure_2005_06.xlsx',1)

expenditures_2005<-expen_2005%>%
  rename(Species_sci="Species (50 CFR Part 17)", Class="Rank", FWS_total="FWS\r\nTotal", Other_fed="Other Fed", Fed_total="Fed Total", States_total="States Total", Species_total="Species Total")%>% #rename variables
  filter(!is.na(Species_sci))%>%
  filter(!is.na(Class))%>%
  mutate(temp=cumsum(Class=="Clams"))%>%
  filter(temp==0)%>% #select rows before "Fishes subtotal"
  select(-temp)

expenditures_2005<-expenditures_2005%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2005)%>%
  data.frame()


#2006
expen_2006<-read_excel('../dataset/expen/expenditure_2005_06.xlsx',2)

expenditures_2006<-expen_2006%>%
  rename(Species_sci="Species (50 CFR Part 17)", FWS_total="FWS\r\nTotal", Other_fed="Other Fed", Fed_total="Fed Total", States_total="States Total", Species_total="Species Total")%>% #rename variables
  filter(!is.na(Species_sci))%>%
  filter(!is.na(Class))%>%
  mutate(temp=cumsum(Class=='Clams'))%>%
  filter(temp==0)%>% #select rows before "Fishes subtotal"
  select(-temp)

expenditures_2006<-expenditures_2006%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2006)%>%
  data.frame()

#2007
expen_2007<-read_excel('../dataset/expen/expenditure_2007.xlsx',1)

expenditures_2007<-expen_2007%>%
  rename(Species_sci="Species (50 CFR Part 17)", FWS_total="FWS\r\nTotal", Other_fed="Other Fed", Fed_total="Fed Total", States_total="States Total", Species_total="Species Total")%>% #rename variables
  filter(!is.na(Species_sci))%>%
  filter(!is.na(Class))%>%
  mutate(temp=cumsum(Class=="Clams"))%>%
  filter(temp==0)%>% #select rows before "Fishes subtotal"
  select(-temp)

expenditures_2007<-expenditures_2007%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2007)%>%
  data.frame()

#2008
expen_2008<-read_excel('../dataset/expen/expenditure_2008.xlsx',2)%>%
  select(-starts_with("..."))

expenditures_2008<-expen_2008%>%
  rename(Species_sci="Species\r\n(50 CFR Part 17)",Class="Group\r\nName", FWS_total="FWS Total", Other_fed="Other Fed", Fed_total="Fed Total", States_total="States\r\nTotal", Species_total="Species\r\nTotal")%>% #rename variables
  filter(!is.na(Class))%>%
  filter(!is.na(Species_sci))%>%
  mutate(temp=cumsum(Class=='Clams'))%>%
  filter(temp==0)%>% #select rows before "Fishes subtotal"
  select(-temp)

#Set Species/Subspecies/Location/Year (because bless them for putting 3 variables in one column)
expenditures_2008<-expenditures_2008%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2008)%>%
  data.frame()

#Clean up data
expenditures_2008<-expenditures_2008%>%
  filter(!Species=="17") #indicating rows with headers


#2009
expen_2009<-read_excel('../dataset/expen/expenditure_2009.xlsx',1)%>%
  select(-starts_with("..."))
expenditures_2009<-expen_2009%>%
  rename(Class = "Group",Species_sci="Species (50 CFR Part 17)", FWS_total="FWS Total", Other_fed="Other Fed", Fed_total="Fed Total", States_total="States Total", Species_total="Species Total")%>% #rename variables
  filter(!is.na(Class))%>%
  filter(!is.na(Species_sci))%>%
  mutate(temp=cumsum(Class=='Clams'))%>%
  filter(temp==0)%>% #select rows before "Fishes subtotal"
  select(-temp)

#Set Species/Subspecies/Location/Year (because bless them for putting 3 variables in one column)
expenditures_2009<-expenditures_2009%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2009)%>%
  data.frame()
#Clean up data
expenditures_2009<-expenditures_2009%>%
  filter(!Species=="17") #indicating rows with headers


#2010
expenditures_2010<-read_excel('../dataset/expen/expenditure_2010.xlsx',2)%>%
  select(-starts_with("...")) %>% rename(FWS_total="FWS_Total", Other_fed="Other_Fed", Fed_total="Fed_Total", States_total="States_Total", Species_total="Species_Total")%>%
  filter(!is.na(Class))%>%
  filter(!is.na(Species_sci))%>%
  mutate(temp=cumsum(Class=='Clams'))%>%
  filter(temp==0)%>% #select rows before "Fishes subtotal"
  select(-temp)

#Set Species/Subspecies/Location/Year (because bless them for putting 3 variables in one column)
expenditures_2010<-expenditures_2010%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2010)%>%
  data.frame()
#Clean up data
expenditures_2010<-expenditures_2010%>%
  filter(!Species=="17") #indicating rows with headers


#2011
file <- '../dataset/expen/expenditure_2011.xlsx'
expen_2011 <- excel_sheets(file)[1:30]%>%map_df(., ~ read_excel(file, sheet = .x))
expen_2011<-expen_2011%>%
  #species is stored in a different column
  mutate(Species_2_filled=!is.na(`Species (50 CFR\r\nPart 17)`)&is.na(`Species (50 CFR`))%>% 
  mutate(`Species (50 CFR`=ifelse(Species_2_filled==TRUE,`Species (50 CFR\r\nPart 17)`,`Species (50 CFR`))%>%
  select(-Species_2_filled)%>%
  #concatenate descriptions
  mutate(temp=cumsum(!is.na(Rank)|is.na(`Species (50 CFR`)))%>%
  group_by(temp)%>%
  mutate(`Species (50 CFR`=str_c(`Species (50 CFR`, collapse=" "))%>%
  filter(!is.na(Rank)&!is.na(`Species Total`))%>%
  ungroup()%>%
  select(-`Species (50 CFR\r\nPart 17)`,-temp)

expen_2011$`Group Name`[is.na(expen_2011$`Group Name`)]<-0 #set NA's as 0

expenditures_2011<-expen_2011%>%
  rename(Class=`Group Name`, Species=`Species (50 CFR`, FWS_total="FWS Total", Other_fed="Other Fed", Fed_total="Fed Total", States_total="States Total", Species_total="Species Total")%>% #rename variables
  filter(!is.na(Class))%>%
  mutate(temp=cumsum(Class=='Clams'))%>% #set rows before "Fishes subtotal" to 0
  filter(temp==0)%>% #select rows before "Fishes subtotal"
  select(-temp)%>% 
  mutate(temp=cumsum(!Class=="Group Name" & !sapply(Class,nchar)<=3))%>% #set Classes
  group_by(temp)%>%
  mutate(Class=dplyr::first(Class))%>%
  ungroup()%>%
  select(-temp)

expenditures_2011$Class<-as.factor(expenditures_2011$Class)
expenditures_2011$Class<-recode(expenditures_2011$Class, "Mammals"="Mammalia","Birds"="Aves","Reptiles"="Reptilia","Amphibians"="Amphibia", "Fishes"="Actinopteri")

#Set Species/Subspecies/Location/Year (because bless them for putting 3 variables in one column)
expenditures_2011<-expenditures_2011%>%
  mutate(Species_loc=str_split(Species," - "))%>% #split by "-" into c(species,location)
  mutate(Species_sci=sapply(Species_loc, "[", 1), #get Species/Location cols
         Location=sapply(Species_loc, "[", 2))%>%
  select(-Species_loc)%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  mutate(Scientific=gsub(" - |- |-\\r\n| -|", "",Scientific))%>%
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2011)


#2012
expenditures_2012<-read_excel('../dataset/expen/expenditure_2012.xlsx')%>%
  select(-starts_with("...")) %>% rename(Other_fed="Other_Fed", Fed_total="Fed_Total", States_total="States_Total", Species_total="Species_Total")%>%
  filter(!is.na(Species_sci))%>%
  mutate(temp=cumsum(Class=='Clams'))%>%
  filter(temp==0)%>% #select rows before "Clams"
  select(-temp)%>%
  filter(!is.na(Class))

#Set Species/Subspecies/Location/Year (because bless them for putting 3 variables in one column)

expenditures_2012<-expenditures_2012%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2012)%>%
  data.frame()
#Clean up data
expenditures_2010<-expenditures_2010%>%
  filter(!Species=="17") #indicating rows with headers

expenditures_2013<-read_excel('../dataset/expen/expenditure_2013.xlsx')%>%
  select(-starts_with("...")) %>% rename(Other_fed="Other_Fed", Fed_total="Fed_Total", States_total="States_Total", Species_total="Species_Total")%>%
  filter(!is.na(Species_sci))%>%
  mutate(temp=cumsum(Class=='Clams'))%>%
  filter(temp==0)%>% #select rows before "Clams"
  select(-temp)%>%
  filter(!is.na(Class))


#2013
expenditures_2013<-expenditures_2013%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2013)%>%
  data.frame()
#Clean up data
expenditures_2013<-expenditures_2013%>%
  filter(!Species=="17") #indicating rows with headers


#2014
expenditures_2014<-read_excel('../dataset/expen/expenditure_2014.xlsx')%>%
  select(-starts_with("...")) %>% rename(Other_fed="Other_Fed", Fed_total="Fed_Total", States_total="States_Total", Species_total="Species_Total")%>%
  filter(!is.na(Species_sci))%>%
  mutate(temp=cumsum(Class=='Clams'))%>%
  filter(temp==0)%>% #select rows before "Clams"
  select(-temp)%>%
  filter(!is.na(Class))

#Set Species/Subspecies/Location/Year (because bless them for putting 3 variables in one column)
expenditures_2014<-expenditures_2014%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2014)%>%
  data.frame()
#Clean up data
expenditures_2014<-expenditures_2014%>%
  filter(!Species=="17") #indicating rows with headers


#2015
expenditures_2015<-read_excel('../dataset/expen/expenditure_2015.xlsx')%>%
  select(-starts_with("..."))%>% rename(Other_fed="Other_Fed", Fed_total="Fed_Total", States_total="States_Total", Species_total="Species_Total")%>%
  filter(!is.na(Species_sci))%>%
  mutate(temp=cumsum(Class=='Clams'))%>%
  filter(temp==0)%>% #select rows before "Clams"
  select(-temp)%>%
  filter(!is.na(Class))

#Set Species/Subspecies/Location/Year (because bless them for putting 3 variables in one column)
expenditures_2015<-expenditures_2015%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2015)%>%
  data.frame()
#Clean up data
expenditures_2015<-expenditures_2015%>%
  filter(!Species=="17") #indicating rows with headers


#2016
expenditures_2016<-read_excel('../dataset/expen/expenditure_2016.xlsx')%>%
  select(-starts_with("..."))%>% rename(Other_fed="Other_Fed", Fed_total="Fed_Total", States_total="States_Total", Species_total="Species_Total")%>%
  filter(!is.na(Species_sci))%>%
  mutate(temp=cumsum(Class=='Clams'))%>%
  filter(temp==0)%>% #select rows before "Clams"
  select(-temp)%>%
  filter(!is.na(Class))

expenditures_2016<-expenditures_2016%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2016)%>%
  data.frame()
#Clean up data
expenditures_2016<-expenditures_2016%>%
  filter(!Species=="17") #indicating rows with headers


#2017
expenditures_2017<-read_excel('../dataset/expen/expenditure_2017.xlsx')%>%
  select(-starts_with("...")) %>% filter(!is.na(Species_sci))%>% rename(Other_fed="Other_Fed", Fed_total="Fed_Total", States_total="States_Total", Species_total="Species_Total")%>%
  filter(!is.na(Species_sci))%>%
  mutate(temp=cumsum(Class=='Clams'))%>%
  filter(temp==0)%>% #select rows before "Clams"
  select(-temp)%>%
  filter(!is.na(Class))

#Set Species/Subspecies/Location/Year (because bless them for putting 3 variables in one column)
expenditures_2017<-expenditures_2017%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),brRead(Species_sci),Species_sci))%>% #if there is no parentheses at all
  mutate(Scientific=ifelse(grepl("\\(",Species_sci),rmBrRead(Scientific),Scientific))%>% #if there is still parentheses after brRead
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1))%>%
  relocate(Species, .after = Scientific)%>%
  mutate(Year=2017)%>%
  data.frame()
#Clean up data
expenditures_2017<-expenditures_2017%>%
  filter(!Species=="17") #indicating rows with headers


## expnditures_ts


expen_selection<-function(data){
  data<-data%>%select(Class, Genus, Species, Subspecies, FWS_total, Other_fed, Fed_total, States_total, Species_total, Year)
  data$FWS_total%<>%as.numeric(unlist(data$FWS_total))
  data$Other_fed%<>%as.numeric(unlist(data$Other_fed))
  data$Fed_total%<>%as.numeric(unlist(data$Fed_total))
  data$States_total%<>%as.numeric(unlist(data$States_total))
  data$Species_total%<>%as.numeric(unlist(data$Species_total))
  data$Year%<>%as.numeric(unlist(data$Year))
  data$Class%<>%as.character(unlist(data$Class))
  data$Genus%<>%as.character(unlist(data$Genus))
  data$Species%<>%as.character(unlist(data$Species))
  data$Subspecies%<>%as.character(unlist(data$Subspecies))
  return(data)
}

expenditures_list<-list(
  expenditures_2000,
  expenditures_2001,
  expenditures_2002,
  expenditures_2003,
  expenditures_2004,
  expenditures_2005,
  expenditures_2006,
  expenditures_2007,
  expenditures_2008,
  expenditures_2009,
  expenditures_2010,
  expenditures_2011,
  expenditures_2012,
  expenditures_2013,
  expenditures_2014,
  expenditures_2015,
  expenditures_2016,
  expenditures_2017
)%>%lapply(expen_selection)

#Vertical join by columns (time series format)
expenditures_ts<-map_df(expenditures_list, rbind)%>%filter(!nchar(Year)==1)


## LPI_red_expen_ts
#Coerce uniformity along join keys by setting to lowercase
merged_timeseries<-merged_timeseries %>%
  mutate(Class = tolower(Class),
         Species = tolower(Species),
         Subspecies = tolower(Subspecies),
         Genus = tolower(Genus))

expenditures_ts<-expenditures_ts%>%
  mutate(Class = tolower(Class),
         Species = tolower(Species),
         Subspecies = tolower(Subspecies),
         Genus = tolower(Genus))

LPI_red_expen_ts<-merged_timeseries%>%left_join(.,expenditures_ts,by=c("Year","Genus", "Species", "Class"))
LPI_red_expen_ts$Class<-as.factor(LPI_red_expen_ts$Class)

LPI_red_expen_ts<-LPI_red_expen_ts%>%group_by(ID)%>%mutate(Countz=(Count-mean(Count))/sd(Count))

## expenditures_FWS_ts
expenditures_ts<-left_join(expenditures_ts,LPI_data%>%mutate(Genus = tolower(Genus))%>%dplyr::select(Common_name, Genus, Species),by=c("Genus","Species"))

FWS<-read.csv('../dataset/FWS_full.csv')%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Scientific.Name),rmBrRead(Scientific.Name),Scientific.Name))%>% #if there is no parentheses at all
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=tolower(sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1)))

FWS_recovery<-read.csv('../dataset/FWS_recovery.csv')%>%
  rowwise%>% #subset by row
  mutate(Scientific=ifelse(grepl("\\(",Species.Scientific.Name),rmBrRead(Species.Scientific.Name),Species.Scientific.Name))%>% #if there is no parentheses at all
  ungroup()%>%
  mutate(Species=ifelse( #create Species variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3, #if Species is format: (Family Species Subspecies)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",2), #then return 2nd to last element (Species)
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),tail,1)))%>% #else return last element (Species)
  mutate(Subspecies=ifelse( #create Subspecies variable
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),length)==3,
    sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),"[",3),
    NA)
  )%>%
  mutate(Genus=tolower(sapply(strsplit(Scientific, "\\s{2,}| |\\)|\\(|\r\n"),head,1)))%>%
  select(-Scientific,-Species.Scientific.Name, -Species.Common.Name, -Recovery.Document.Title_url,-Species.Population, -Species.Scientific.Name_url, -ECOS.Species.Group, -ESA.Listing.Status)

expenditures_FWS_ts<-left_join(expenditures_ts,FWS, by=c("Genus","Species","Subspecies"))%>%distinct(.keep_all = TRUE)%>%filter(!is.na(Scientific.Name))%>%left_join(FWS_recovery,by=c("Genus","Species","Subspecies"))

```

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(DT)
library(plotly)
library(shiny)
library(crosstalk)
library(sunburstR)
library(sf)
library(leaflet)
data<-expenditures_FWS_ts
shared_data <- SharedData$new(data)
```
Map
=======================================================================
```{r}
#get coordinates
data_alt<-data%>%
  distinct(Common.Name,Genus,Species,Year,Species_total,.keep_all = TRUE)%>%
  filter(!is.na(Scientific.Name))%>%
  group_by(ESA.Listing.Status)%>%
  mutate(n=n())%>%
  filter(n>100)%>%
  filter(!nchar(Range.Envelope)==0)%>%
  rowwise%>%
  mutate(coord=gsub("POLYGON|\\(|\\)",'', Range.Envelope))%>%
  mutate(coord=strsplit(coord,",| "))%>%
  mutate(Conservation.Plan.Type=gsub("^$|^ $", "N/A", Conservation.Plan.Type))

#turn coordinate list from string to numeric
data_alt$coord<-lapply(data_alt$coord, as.numeric)
  
#turn coordinates into polygons       
data_alt<-data_alt%>%
  mutate(polygon=matrix(coord,ncol=2,byrow=TRUE)%>%
           as.data.frame()%>%
           rename(lat="V1",lon="V2")%>%
           st_as_sf(coords = c("lat", "lon")) %>%
           summarise(geometry = st_combine(geometry)) %>%
           st_cast("POLYGON")%>%
#get centroids
           st_centroid(),
#get lat and long
         lat = unlist(polygon)[2],
         long = unlist(polygon)[1]
         )%>%
  ungroup()

data_alt$ESA.Listing.Status<-as.factor(data_alt$ESA.Listing.Status)
data_alt$Conservation.Plan.Type<-factor(data_alt$Conservation.Plan.Type, levels=c("NA","HCP", "SHA", "CCA", "CCAA"))

shared_data<-data_alt%>%
  SharedData$new()

```

Inputs {.sidebar data-width=200}
-------------------------------------
```{r}
filter_select(id = "Year", label = "Year", 
                       sharedData = shared_data, group = ~Year)

filter_select(id="ESA Status", label="ESA Status",
                       sharedData = shared_data, group=~ESA.Listing.Status)

filter_select(id="Class", label="Class", 
                       sharedData = shared_data, group=~Class)

filter_select(id="Common Name", label="Species Name", 
                       sharedData = shared_data, group=~Common.Name)

filter_checkbox(id="Conservation.Plan.Type", label="Conservation Plan Type", 
                       sharedData = shared_data, group=~Conservation.Plan.Type)

filter_slider(id="Expenditure", label="Expenditure", 
                       sharedData = shared_data, column=~Species_total)
```

Row
-----------------------------------------------------------------------
### Species Map

```{r}
library(htmltools)

#color palette by ESA Status
pal <- colorFactor(
  palette = 'Spectral',
  domain = data_alt$ESA.Listing.Status
)

#species labels with Common Name, Year, Species total, ESA Status
labels <- sprintf("<strong>%s %.0f</strong><br/>Expenditure Total: %.0f<br/>Current ESA Status: %s",
  data_alt$Common.Name, data_alt$Year, data_alt$Species_total, data_alt$ESA.Listing.Status
) %>% 
  lapply(htmltools::HTML)

map <- shared_data%>%
  leaflet()%>%
  addTiles()%>%
  addCircles(weight = 1,
             radius = ~sqrt(Species_total)* 50,
             label = labels,
             fillColor =~pal(ESA.Listing.Status),
             fillOpacity = 0.3,
             highlight = highlightOptions(weight = 5,color = "#5D6D7E", fillOpacity = 0.9)
             )%>%
  addLegend(pal = pal,
             values = ~ESA.Listing.Status, 
             group = "circles", 
             position = "bottomright", 
             title = "ESA Status")

map
```

Species Expenditure Dashboard
=======================================================================

Row
-----------------------------------------------------------------------
### Spending by Species

```{r}
data_alt<-data%>%
  distinct(Genus,Species,Species_total,.keep_all = TRUE)%>%
  filter(!is.na(Scientific.Name))%>%
  group_by(ESA.Listing.Status)%>%
  mutate(n=n())%>%
  filter(n>150)%>%
  ungroup()%>%
  group_by(Common.Name,Year,ESA.Listing.Status,Class)%>%
  summarize(FWS=sum(FWS_total),`Other Federal`=sum(Other_fed),States=sum(States_total))%>%
  ungroup%>%
  group_by(ESA.Listing.Status,Year)%>%
  pivot_longer(c(FWS,`Other Federal`,States))

shared_data<-data_alt%>%
  SharedData$new()

fig <- shared_data%>%
  plot_ly(type='pie', 
          labels = ~Common.Name, 
          values = ~value,
          textinfo = "none")%>% 
  layout(title = "Spending by Species", showlegend = F)

bscols(widths=c(2,NA),
       list(
         filter_select(id = "Year", label = "Year", sharedData = shared_data, group = ~Year),
         filter_select(id = "funding", label = "Funding Source", sharedData = shared_data, group = ~name),
         filter_checkbox(id = "Class", label = "Class", sharedData = shared_data, group = ~Class)
         ), fig)
```

### Sunburst Spending by Species
```{r}
data_alt<-data%>%
  distinct(Genus,Species,Species_total,.keep_all = TRUE)%>%
  filter(!is.na(Scientific.Name))%>%
  group_by(ESA.Listing.Status)%>%
  mutate(n=n())%>%
  filter(n>150)%>%
  ungroup()%>%
  mutate(path=paste(Class, Genus, Species, Year, sep="-"))%>%
  select(path, Species_total)

fig<-sunburst(data_alt,legend=FALSE)

fig
```

Row {.tabset}
-----------------------------------------------------------------------

### Expenditure by Class

```{r}
data_alt<-data%>%
  distinct(Genus,Species,Species_total,.keep_all = TRUE)%>%
  filter(!is.na(Scientific.Name))%>%
  group_by(ESA.Listing.Status)%>%
  mutate(n=n())%>%
  filter(n>100)%>%
  ungroup()%>%
  group_by(Class,Year)%>%
  summarize(FWS=sum(FWS_total),`Other Federal`=sum(Other_fed),States=sum(States_total))%>%
  pivot_longer(c(FWS,`Other Federal`,States))

  
shared_data<-data_alt%>%
  SharedData$new()

fig<-shared_data%>%
  plot_ly( x=~Year, y=~value, type = 'bar', name=~Class, color=~Class, colors="Paired",title="Expenditure by Class")%>%
    layout(barmode = 'stack',yaxis=list(title="Expenditure ($)"))

bscols(widths=c(2,NA),
       list(
         filter_slider(id = "Year", label = "Year",sharedData = shared_data, column = ~Year),
         filter_select(id = "funding", label = "Funding Source", sharedData = shared_data, group = ~name)
         ),
       fig)
```


### FWS Expenditures by ESA Status

```{r}
data_alt<-data%>%
  distinct(Common.Name,Genus,Species,Year,Species_total,.keep_all = TRUE)%>%
  group_by(ESA.Listing.Status)%>%
  mutate(n=n())%>%
  filter(n>60)%>%
  ungroup()%>%
  group_by(ESA.Listing.Status,Year)%>%
  mutate(FWS=sum(FWS_total),`Other Federal`=sum(Other_fed),States=sum(States_total))%>%
  pivot_longer(c(FWS,`Other Federal`,States))

shared_data<-data_alt%>%
  SharedData$new()

fig<-shared_data%>%plot_ly(x=~Year,
          y=~value,
          text=~Common.Name,
          name=~ESA.Listing.Status,
          color=~ESA.Listing.Status,
          type='bar',
          colors="Paired",
          title="FWS Expenditures by ESA Status")%>%
  layout(barmode = 'stack',legend = list(orientation = 'h'), yaxis=list(title="Expenditure ($)"))

bscols(widths=c(2,NA),
       list(
         filter_slider(id = "Year", label = "Year",sharedData = shared_data, column = ~Year),
         filter_select(id = "funding", label = "Funding Source", sharedData = shared_data, group = ~name)
         ),
       fig)
```

Species Population Dashboard
=======================================================================

Row
-----------------------------------------------------------------------
### Species Population Trends

```{r}

```

